[tool.poetry]
name = "weaviate"
version = "0.1.0"
description = ""
authors = ["Frank Lu <frank.lu@swag.live>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
weaviate-client = "^3.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
